services:
  db:
    container_name: refly_db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=refly
      - POSTGRES_USER=refly
      - POSTGRES_PASSWORD=test
  minio:
    container_name: refly_minio
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  redis:
    container_name: refly_redis
    image: redis/redis-stack
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data
  qdrant:
    container_name: refly_qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage:z
    restart: always
  elasticsearch:
    container_name: refly_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch-entrypoint.sh:/elasticsearch-entrypoint.sh
    restart: always
    entrypoint: ['/elasticsearch-entrypoint.sh']
    healthcheck:
      test: ['CMD-SHELL', 'curl -s http://localhost:9200 >/dev/null || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
  minio_data:
  redis_data:
  qdrant_data:
  elasticsearch_data:
