include:
  - path: docker-compose.middleware.yml
services:
  api:
    image: reflyai/refly-api:latest
    container_name: refly_api
    depends_on:
      - db
      - minio
      - redis
      - qdrant
      - elasticsearch
    ports:
      - 5800:5800
      - 5801:5801
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=http://minio
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://refly:test@db:5432/refly?schema=refly
      - QDRANT_HOST=qdrant
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  web:
    image: reflyai/refly-web:latest
    container_name: refly_web
    ports:
      - 5700:80
    restart: always
