version: '3.4'
include:
  - path: docker-compose.dev.yml
services:
  api:
    build: ../../apps/api
    container_name: refly_api
    depends_on:
      - db
      - minio
      - redis
      - qdrant
      - elasticsearch
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=http://minio
      - DATABASE_URL=postgresql://refly:test@db:5432/refly
      - OTEL_URL=http://172.20.0.6:4318
      - QDRANT_HOST=http://qdrant
