version: '3'
services:
  db:
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=refly
      - POSTGRES_USER=refly
      - POSTGRES_PASSWORD=test
  reflyd:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://refly:test@db:5432/refly
      - OTEL_URL=http://172.20.0.6:4318
