version: '3'
services:
  db:
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=refly
      - POSTGRES_USER=refly
      - POSTGRES_PASSWORD=test
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
  reflyd:
    build: .
    depends_on:
      - db
      - minio
      - redis
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=http://minio
      - DATABASE_URL=postgresql://refly:test@db:5432/refly
      - OTEL_URL=http://172.20.0.6:4318
