version: "3"
services:
  reflyd:
    image: reflyd:latest
    build:
      context: ../../reflyd
      dockerfile: Dockerfile
    command: >
      node dist/main.js
    depends_on:
      - db
      - redis
      - qdrant
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://db:27017/refly
      - QDRANT_URL=qdrant:6333
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db_volume:/data/db
    restart: always
  redis:
    image: redis/redis-stack:latest
    restart: always
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    env_file:
      - .env
    volumes:
      - vector_volume:/qdrant/storage
  # This container name cannot have an underscore in it due to Vespa expectations of the URL
  nginx:
    image: nginx:1.23.4-alpine
    restart: always
    depends_on:
      - reflyd
    ports:
      - "80:80"
    volumes:
      - ../config:/etc/nginx/conf.d

volumes:
  vector_volume:
  db_volume:
