name: Deploy Web To Staging

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-web-base.yml
    secrets: inherit
    with:
      environment: staging
      project-name: refly-app-staging
