name: Deploy Web

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project-name:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: refly-ai
          SENTRY_PROJECT: web
        with:
          environment: ${{ inputs.environment }}

      - name: Remove source map files
        run: find apps/web/dist/assets -name "*.map" -type f -delete

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ inputs.project-name }}
          branch: main # always main, to ensure production deployment
          workingDirectory: apps/web
          directory: dist
