name: Deploy Web To Prod

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: production
      web_deploy_project: refly-app
