name: Deploy API To Prod

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy-api-base.yml
    with:
      environment: production
      ecs-cluster: Prod
      ecs-service: prod
    secrets: inherit
