name: Deploy API To Staging

on:
  push:
    branches-ignore:
      - release
    paths:
      - 'apps/api/**'
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-api-base.yml
    with:
      environment: staging
      ecs-cluster: Prod
      ecs-service: staging
    secrets: inherit
