name: Deploy Web To Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: staging
      web_deploy_project: refly-app-staging
