name: Publish API Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/api/**'
  workflow_dispatch:

jobs:
  publish:
    name: Publish API Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/refly-api:${{ github.sha }}
