name: Upload Web Artifacts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for'
        required: true
        type: choice
        options:
          - staging
          - production
        default: 'staging'

jobs:
  build:
    name: Build and Upload
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  upload:
    name: Upload Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
          retention-days: 5
